// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMCdP2SVvVYxlaN_qmXK51IKxrPUP3UlU',
    appId: '1:432859725374:web:72a9d87265c694c7ad5b6f',
    messagingSenderId: '432859725374',
    projectId: 'benji-crm',
    authDomain: 'benji-crm.firebaseapp.com',
    storageBucket: 'benji-crm.appspot.com',
    measurementId: 'G-4YD8PF5306',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyMKgWws1uhZq7aH7NYhKqWSbSANHnD78',
    appId: '1:432859725374:ios:b22a0150f667a770ad5b6f',
    messagingSenderId: '432859725374',
    projectId: 'benji-crm',
    storageBucket: 'benji-crm.appspot.com',
    iosBundleId: 'com.benjiexpress.crm.ios',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuC_kqSIQXoB2_rMY6cxYhAfkEPq3TT9Q',
    appId: '1:432859725374:android:4eba048ab417eb51ad5b6f',
    messagingSenderId: '432859725374',
    projectId: 'benji-crm',
    storageBucket: 'benji-crm.appspot.com',
  );
}
